### PR TITLE
Fix dll location & update max_pin in run_exports

### LINKED ISSUE #16: DLLs are in the wrong folder!
```cmd
>dir xxx\_test_env\Library\lib | findstr /i event
06/16/2019  10:34 PM           288,256 event.dll
06/16/2019  10:34 PM           133,890 event.lib
06/16/2019  10:34 PM           177,152 event_core.dll
06/16/2019  10:34 PM            83,996 event_core.lib
06/16/2019  10:34 PM           121,856 event_extra.dll
06/16/2019  10:34 PM            54,546 event_extra.lib
06/16/2019  10:34 PM            24,576 event_openssl.dll
06/16/2019  10:34 PM             3,756 event_openssl.lib
```

The DLLs should be in the bin folder.

### PR DESCRIPTION
**Pull request by nehaljwani**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Resolves #16

### CODE REVIEW

**Comment by nehaljwani** [comment]
This change is required for upgrading mysql which I am working on at https://github.com/nehaljwani/mysql-feedstock/commits/8.0.19

**Comment by nehaljwani** [comment]
I've also updated the max_pin here. It's a small change for maximum benefit :stuck_out_tongue_winking_eye: 

cc @jakirkham @CJ-Wright @xhochy @beckermr @sodre

**Comment by beckermr** [comment]
Weird. I think the run export in this package was wrong. The pinnings had x.x.x

https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L216

**Comment by nehaljwani** [comment]
Yes, there is a relevant discussion at https://github.com/conda-forge/libevent-feedstock/pull/15

**Comment by beckermr** [comment]
Yup. This will need a fix in the repo data patches.

**Comment by nehaljwani** [comment]
Sure, but the repodata hotfix shouldn't block this PR, as it is not building a new version.

**Comment by beckermr** [comment]
yup

**Pull request merged**
